### ISSUE TITLE
idea 2020.3.2 leeks-1.8.6 插件报错

### ISSUE THREAD

**Issue by xyzzxy123** [huage2580/leeks#104]
com.intellij.diagnostic.PluginException: Cannot create class FundWindow [Plugin: com.huage2580.leeks]
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:725)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateExtensionWithPicoContainerOnlyIfNeeded(ComponentManagerImpl.kt:754)
	at com.intellij.openapi.wm.Too
![QQ截图20210318171150](https://user-images.githubusercontent.com/30489753/111601145-0c76d980-880d-11eb-8985-94b7cd48d46d.png)
lWindowEP.getToolWindowFactory(ToolWindowEP.java:121)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$$special$$inlined$processDescriptors$2.accept(ToolWindowManagerImpl.kt:2118)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$$special$$inlined$processDescriptors$2.accept(ToolWindowManagerImpl.kt:90)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:296)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:158)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.<init>(ToolWindowManagerImpl.kt:2161)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:733)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:49)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:37)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$future$1.run(ComponentManagerImpl.kt:890)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:684)
	... 31 more
Caused by: java.lang.NoClassDefFoundError: com/github/promeg/pinyinhelper/Pinyin
	at utils.PinYinUtils.toPinYin(PinYinUtils.java:7)
	at utils.WindowUtils.<clinit>(WindowUtils.java:24)
	at handler.StockRefreshHandler.<clinit>(StockRefreshHandler.java:36)
	at StockWindow.factoryHandler(StockWindow.java:152)
	at StockWindow.<init>(StockWindow.java:108)
	at FundWindow.<init>(FundWindow.java:41)
	... 36 more
Caused by: java.lang.ClassNotFoundException: com.github.promeg.pinyinhelper.Pinyin PluginClassLoader[PluginDescriptor(name=Leeks, id=com.huage2580.leeks, path=C:\Users\A-user\AppData\Roaming\JetBrains\PhpStorm2020.3\plugins\leeks-1.8.6.jar, version=1.8.6)] com.intellij.ide.plugins.cl.PluginClassLoader@49a21217
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 42 more

**Comment by dengerYang** [comment]
#86 #102 一样，没有插件没有安装正确：正确操作是直接选择zip包进行安装，不要解压zip包

**Comment by xyzzxy123** [comment]
> #86 #102 一样，没有插件没有安装正确：正确操作是直接选择zip包进行安装，不要解压zip包

好的我试试
