### ISSUE TITLE
双击打不开图表，报错

### ISSUE THREAD

**Issue by CraigMChen** [huage2580/leeks#122]
**请确保你完整仔细的阅读了Readme，对关闭的issue进行了搜索，任何重复bug直接close不予回复**  
**IDEA版本(Help-About里面完整复制出来)**  
```
GoLand 2021.1.2
Build #GO-211.7442.27, built on May 25, 2021
Runtime version: 11.0.11+9-b1341.57 aarch64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.completion.variant.limit=500, suggest.all.run.configurations.from.context=true
Non-Bundled Plugins: IdeaVIM (0.68), com.huage2580.leeks (1.9.1), com.jetbrains.ChooseRuntime (1.2)
```
**插件版本号**  
```
v1.9.1
```
**错误日志**
```
com.intellij.util.IncorrectOperationException: Sorry but parent: Project(name=leetcode, containerState=DISPOSE_COMPLETED, componentStore=/Users/craig/go/src/github.com/craigmchen/leetcode) (disposed) has already been disposed (see the cause for stacktrace) so the child: com.intellij.ui.tabs.layout.singleRowLayout.ScrollableSingleRowLayout@21f73447 will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:55)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:73)
	at com.intellij.ui.tabs.impl.JBTabsImpl.updateTabsLayout(JBTabsImpl.java:3127)
	at com.intellij.ui.tabs.impl.JBTabsImpl.<init>(JBTabsImpl.java:375)
	at com.intellij.ui.tabs.impl.JBTabsImpl.<init>(JBTabsImpl.java:226)
	at com.intellij.ui.tabs.impl.JBTabsImpl.<init>(JBTabsImpl.java:222)
	at utils.PopupsUiUtil.showImageByFundCode(PopupsUiUtil.java:34)
	at FundWindow$2.mousePressed(FundWindow.java:110)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6649)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.ui.table.JBTable.processMouseEvent(JBTable.java:744)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```  
**这里描述你的问题**
```
双击任意一行数据想要打开图表，都会报错，图表出不来。重启IDE可以解决，过段时间又出现。
```

**Comment by huage2580** [comment]
是所有都会吗，股票和基金面板

**Comment by huage2580** [comment]
v1.9.2修复

**Comment by dengerYang** [comment]
出现场景原因：
  打开A项目，然后再开B项目，在A项目中打开插件，又在B项目打开插件，接着点击A项目的插件的数据，然后关闭B项目，B项目已经销毁了，导致点击A项目的窗口失败；
临时解决办法：
 点击A项目插件的标题栏中的其它项【Fund、Stock、Coin】任意一个，让程序获取到当前idea的project，后续再想办法代码优化

**Comment by CraigMChen** [comment]
@dengerYang 按你说的方法确实可以解决问题
