### ISSUE TITLE
兼容性问题,无法兼容最新版本2024.1

### ISSUE THREAD

**Issue by songshengping** [huage2580/leeks#177]
**请确保你完整仔细的阅读了Readme，对关闭的issue进行了搜索，任何重复bug直接close不予回复**  
**IDEA版本(Help-About里面完整复制出来)**  
```
版本内容
```
**插件版本号**  
```
[v2.3.0 fix](https://github.com/WoChen5770/leeks/releases/tag/2.3.0)
```
**错误日志**
```
如果有，请复制出来
![image](https://github.com/huage2580/leeks/assets/50539147/797d567d-dae9-4c9e-9654-734a0cffd9d1)

```  
**这里描述你的问题**
```
```

**Comment by WoChen5770** [comment]
https://github.com/WoChen5770/leeks/releases/tag/2.4.0

**Comment by RainyQing** [comment]
@WoChen5770 大佬还会继续优化吗?

**Comment by WoChen5770** [comment]
> @WoChen5770 大佬还会继续优化吗?

现在用起来有问题吗？我最近没用插件看了

**Comment by RainyQing** [comment]
倒是没啥问题 , 我想继续优化 , 加点功能 , 但是加了没生效 @WoChen5770

**Comment by zhusensir** [comment]
idea2024.2.1报错
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'StockWindow$4' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.huage2580.leeks]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by RainyQing** [comment]
https://github.com/RainyQing/leeks/releases/tag/v2.5.0 @songshengping @zhusensir  试试这个 , 我更新适配了最新版idea
