### ISSUE TITLE
idea2024.2.1报错，无法使用

### ISSUE THREAD

**Issue by zhusensir** [huage2580/leeks#182]
idea2024.2.1报错
com.intellij.diagnostic.PluginException: ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon. 'StockWindow$4' must override getActionUpdateThread() and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.huage2580.leeks]
at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by RainyQing** [comment]
https://github.com/RainyQing/leeks/releases/tag/v2.5.0 试试这个 , 我更新适配2024.3 @zhusensir
